[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "20" }

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200