[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "22.18.0" } # Match the Node version from your log

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200
